### ISSUE TITLE
unknown error when connecting (and one more thing)

### ISSUE THREAD

**Issue by summerz** [valentinradu/WhiteRaccoon#7]
Hi,

I'm using your library (thank you) for uploading files to ftp server. 

but I got an error when I try to connect to a server.

the error is 'unknown error' and I can see that it's from line 476 (case NSStreamEventErrorOccurred: ...) in the stream delegate [start at line 441] 

can you give me any help for this?

thank you.

p.s.) I also want to ask you that 'passive mode (in init()) is working properly? ftp servers with active mode seems not to connected when I use your library.

**Comment by ghost** [comment]
Are you using a project with Objective-C ARC?

**Comment by summerz** [comment]
No I don't. do you have any idea?

**Comment by Stalevar** [comment]
At first I thank author for the good FTP class!

I've got the same error.
And I spent a lot of time to find answer. And actually it was my silly fault
When I assigned downloadFile.hostname I wrote full URL with "ftp://" prefix
Class will add this prefix itself

So instead of downloadFile.hostname = @"ftp://qwerty.com"
I needed to write downloadFile.hostname = @"qwerty.com"

Probably you have the same
